version: '3'
services:
  blog:
    command: jekyll serve
    image: jekyll/jekyll:latest
    volumes:
      - ./blog-site:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
    ports:
      - 4000:4000
      